# version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    container_name: frontend
    # image name
    image: frontend
    # this is the directory where the Dockerfile for the web service is located
    build: ./frontend
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: http://localhost:8000
    # anything mentioned under develop will be watched for changes by docker compose watch and it will perform the action mentioned
    develop:
      # we specify the files to watch for changes
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container if there are any changes
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        # it'll watch for changes in the frontend directory and sync the changes with the container real time
        - path: ./frontend
          target: /app
          action: sync

  backend:
    container_name: backend
    image: backend
    build: ./backend
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL= mysql://avnadmin:AVNS_2lZrrkAPjhxeX4tZcY_@mysql-dental-his-dental-his.d.aivencloud.com:20366/defaultdb?ssl-mode=REQUIRED # Reference to the .env file
    # establish docker compose watch mode for the backend service
    develop:
      # specify the files to watch for changes
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container and image if there are any changes
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild

        # it'll watch for changes in the backend directory and sync the changes with the container real time
        - path: ./backend
          target: /app
          action: sync
