export const MOCK_TABLE_DATA = {
  upcoming: [
    {
      id: 1,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Surgery",
      dateTime: "2024/01/31, 15:00",
      paymentStatus: "Deposit",
    },
    {
      id: 2,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Consultancy",
      dateTime: "2024/02/01, 09:30",
      paymentStatus: "Unpaid",
    },
    {
      id: 3,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Examination",
      dateTime: "2024/02/01, 11:00",
      paymentStatus: "Paid",
    },
    {
      id: 4,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Follow-up",
      dateTime: "2024/02/02, 14:15",
      paymentStatus: "Deposit",
    },
    {
      id: 5,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Surgery",
      dateTime: "2024/02/03, 10:00",
      paymentStatus: "Paid",
    },
    {
      id: 6,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Consultancy",
      dateTime: "2024/02/04, 13:30",
      paymentStatus: "Unpaid",
    },
    {
      id: 7,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Examination",
      dateTime: "2024/02/05, 09:00",
      paymentStatus: "Deposit",
    },
    {
      id: 8,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Follow-up",
      dateTime: "2024/02/06, 15:45",
      paymentStatus: "Paid",
    },
    {
      id: 9,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Surgery",
      dateTime: "2024/02/07, 11:30",
      paymentStatus: "Deposit",
    },
    {
      id: 10,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Consultancy",
      dateTime: "2024/02/08, 14:00",
      paymentStatus: "Unpaid",
    },
    {
      id: 11,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Examination",
      dateTime: "2024/02/09, 10:30",
      paymentStatus: "Paid",
    },
    {
      id: 12,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Follow-up",
      dateTime: "2024/02/10, 13:15",
      paymentStatus: "Deposit",
    },
    {
      id: 13,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Surgery",
      dateTime: "2024/02/11, 09:45",
      paymentStatus: "Paid",
    },
    {
      id: 14,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Consultancy",
      dateTime: "2024/02/12, 15:30",
      paymentStatus: "Unpaid",
    },
    {
      id: 15,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Examination",
      dateTime: "2024/02/13, 11:45",
      paymentStatus: "Deposit",
    },
    {
      id: 16,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Follow-up",
      dateTime: "2024/02/14, 14:30",
      paymentStatus: "Paid",
    },
    {
      id: 17,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Surgery",
      dateTime: "2024/02/15, 10:15",
      paymentStatus: "Deposit",
    },
    {
      id: 18,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Consultancy",
      dateTime: "2024/02/16, 13:45",
      paymentStatus: "Unpaid",
    },
    {
      id: 19,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Examination",
      dateTime: "2024/02/17, 09:15",
      paymentStatus: "Paid",
    },
    {
      id: 20,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Follow-up",
      dateTime: "2024/02/18, 15:15",
      paymentStatus: "Deposit",
    },
  ],
  past: [
    {
      id: 21,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Surgery",
      dateTime: "2023/12/01, 14:00",
      paymentStatus: "Paid",
    },
    {
      id: 22,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Consultancy",
      dateTime: "2023/12/02, 10:30",
      paymentStatus: "Paid",
    },
    {
      id: 23,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Examination",
      dateTime: "2023/12/03, 15:45",
      paymentStatus: "Paid",
    },
    {
      id: 24,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Follow-up",
      dateTime: "2023/12/04, 11:15",
      paymentStatus: "Paid",
    },
    {
      id: 25,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Surgery",
      dateTime: "2023/12/05, 09:00",
      paymentStatus: "Paid",
    },
    {
      id: 26,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Consultancy",
      dateTime: "2023/12/06, 14:30",
      paymentStatus: "Unpaid",
    },
    {
      id: 27,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Examination",
      dateTime: "2023/12/07, 10:45",
      paymentStatus: "Paid",
    },
    {
      id: 28,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Follow-up",
      dateTime: "2023/12/08, 13:15",
      paymentStatus: "Paid",
    },
    {
      id: 29,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Surgery",
      dateTime: "2023/12/09, 15:00",
      paymentStatus: "Paid",
    },
    {
      id: 30,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Consultancy",
      dateTime: "2023/12/10, 11:30",
      paymentStatus: "Paid",
    },
    {
      id: 31,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Examination",
      dateTime: "2023/12/11, 09:45",
      paymentStatus: "Paid",
    },
    {
      id: 32,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Follow-up",
      dateTime: "2023/12/12, 14:15",
      paymentStatus: "Unpaid",
    },
    {
      id: 33,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Surgery",
      dateTime: "2023/12/13, 10:00",
      paymentStatus: "Paid",
    },
    {
      id: 34,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Consultancy",
      dateTime: "2023/12/14, 15:30",
      paymentStatus: "Paid",
    },
    {
      id: 35,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Examination",
      dateTime: "2023/12/15, 11:45",
      paymentStatus: "Paid",
    },
    {
      id: 36,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Follow-up",
      dateTime: "2023/12/16, 13:30",
      paymentStatus: "Paid",
    },
    {
      id: 37,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Surgery",
      dateTime: "2023/12/17, 09:15",
      paymentStatus: "Paid",
    },
    {
      id: 38,
      dentistName: "Dr. Michael Chen",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Consultancy",
      dateTime: "2023/12/18, 14:45",
      paymentStatus: "Unpaid",
    },
    {
      id: 39,
      dentistName: "Dr. Omar El-Hareery",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Examination",
      dateTime: "2023/12/19, 10:30",
      paymentStatus: "Paid",
    },
    {
      id: 40,
      dentistName: "Dr. Sarah Johnson",
      dentistImage: "../assets/images/IMG_1250-2.jpg",
      category: "Follow-up",
      dateTime: "2023/12/20, 15:15",
      paymentStatus: "Paid",
    },
  ],

  // Patient Invoices
  invoices: [
    {
      id: 1,
      category: "Surgery",
      treatment: "Root Canal",
      dateTime: "2024/01/15, 14:00",
      paymentStatus: "Paid",
      insuranceCoverage: "80%",
    },
    {
      id: 2,
      category: "Consultancy",
      treatment: "Dental Examination",
      dateTime: "2024/01/20, 10:30",
      paymentStatus: "Pending",
      insuranceCoverage: "100%",
    },
    {
      id: 3,
      category: "Surgery",
      treatment: "Wisdom Tooth Extraction",
      dateTime: "2024/01/25, 09:00",
      paymentStatus: "Unpaid",
      insuranceCoverage: "60%",
    },
    // Add more invoice entries as needed
  ],

  // Doctor Appointments
  doctorAppointments: [
    {
      id: 1,
      patientName: "John Smith",
      patientImage: "../assets/images/IMG_1250-2.jpg",
      category: "Surgery",
      dateTime: "2024/02/01, 09:00",
    },
    {
      id: 2,
      patientName: "Emily Johnson",
      patientImage: "../assets/images/IMG_1250-2.jpg",
      category: "Consultancy",
      dateTime: "2024/02/01, 10:30",
    },
    {
      id: 3,
      patientName: "Michael Brown",
      patientImage: "../assets/images/IMG_1250-2.jpg",
      category: "Examination",
      dateTime: "2024/02/01, 14:00",
    },
    // Add more doctor appointments as needed
  ],

  // Doctor Patients
  doctorPatients: [
    {
      id: 1,
      patientName: "John Smith",
      patientImage: "../assets/images/IMG_1250-2.jpg",
      age: 35,
      gender: "Male",
      bloodGroup: "A+",
    },
    {
      id: 2,
      patientName: "Emily Johnson",
      patientImage: "/avatars/patient2.jpg",
      age: 28,
      gender: "Female",
      bloodGroup: "O-",
    },
    {
      id: 3,
      patientName: "Michael Brown",
      patientImage: "/avatars/patient3.jpg",
      age: 45,
      gender: "Male",
      bloodGroup: "B+",
    },
    // Add more doctor patients as needed
  ],

  // Admin Appointments
  adminAppointments: [
    {
      id: 1,
      patientName: "John Smith",
      dentistName: "Dr. Omar El-Hareery",
      dateTime: "2024/02/01, 09:00",
      status: "Deposit",
      category: "Surgery",
    },
    {
      id: 2,
      patientName: "Emily Johnson",
      dentistName: "Dr. Sarah Johnson",
      dateTime: "2024/02/01, 10:30",
      status: "Unpaid",
      category: "Consultancy",
    },
    {
      id: 3,
      patientName: "Michael Brown",
      dentistName: "Dr. Michael Chen",
      dateTime: "2024/02/01, 14:00",
      status: "Paid",
      category: "Examination",
    },
    // Add more admin appointments as needed
  ],

  // Admin Inventory
  adminInventory: [
    {
      id: 1,
      equipmentName: "Dental Chair",
      equipmentImage: "/equipment/dental-chair.jpg",
      equipmentQuantity: 5,
      equipmentBrand: "A-dec",
    },
    {
      id: 2,
      equipmentName: "X-Ray Machine",
      equipmentImage: "/equipment/xray.jpg",
      equipmentQuantity: 2,
      equipmentBrand: "Carestream",
    },
    {
      id: 3,
      equipmentName: "Sterilizer",
      equipmentImage: "/equipment/sterilizer.jpg",
      equipmentQuantity: 3,
      equipmentBrand: "Midmark",
    },
    // Add more inventory items as needed
  ],

  // Admin Patients
  adminPatients: [
    {
      id: 1,
      patientName: "John Smith",
      patientImage: "/avatars/patient1.jpg",
      age: 35,
      gender: "Male",
      bloodGroup: "A+",
    },
    {
      id: 2,
      patientName: "Emily Johnson",
      patientImage: "/avatars/patient2.jpg",
      age: 28,
      gender: "Female",
      bloodGroup: "O-",
    },
    {
      id: 3,
      patientName: "Michael Brown",
      patientImage: "/avatars/patient3.jpg",
      age: 45,
      gender: "Male",
      bloodGroup: "B+",
    },
    // Add more admin patients as needed
  ],

  // Admin Doctors
  adminDoctors: [
    {
      id: 1,
      doctorName: "Dr. Omar El-Hareery",
      doctorImage: "/avatars/doctor1.jpg",
      age: 40,
      gender: "Male",
      email: "omar.elhareery@hospital.com",
      status: "Available",
    },
    {
      id: 2,
      doctorName: "Dr. Sarah Johnson",
      doctorImage: "/avatars/doctor2.jpg",
      age: 35,
      gender: "Female",
      email: "sarah.johnson@hospital.com",
      status: "Available",
    },
    {
      id: 3,
      doctorName: "Dr. Michael Chen",
      doctorImage: "/avatars/doctor3.jpg",
      age: 45,
      gender: "Male",
      email: "michael.chen@hospital.com",
      status: "Absent",
    },
    {
      id: 4,
      doctorName: "Dr. Omar El-Hareery",
      doctorImage: "/avatars/doctor1.jpg",
      age: 40,
      gender: "Male",
      email: "omar.elhareery@hospital.com",
      status: "Available",
    },
    {
      id: 5,
      doctorName: "Dr. Sarah Johnson",
      doctorImage: "/avatars/doctor2.jpg",
      age: 35,
      gender: "Female",
      email: "sarah.johnson@hospital.com",
      status: "Available",
    },
    {
      id: 6,
      doctorName: "Dr. Michael Chen",
      doctorImage: "/avatars/doctor3.jpg",
      age: 45,
      gender: "Male",
      email: "michael.chen@hospital.com",
      status: "Absent",
    },
    {
      id: 7,
      doctorName: "Dr. Omar El-Hareery",
      doctorImage: "/avatars/doctor1.jpg",
      age: 40,
      gender: "Male",
      email: "omar.elhareery@hospital.com",
      status: "Available",
    },
    {
      id: 8,
      doctorName: "Dr. Sarah Johnson",
      doctorImage: "/avatars/doctor2.jpg",
      age: 35,
      gender: "Female",
      email: "sarah.johnson@hospital.com",
      status: "Available",
    },
    {
      id: 9,
      doctorName: "Dr. Michael Chen",
      doctorImage: "/avatars/doctor3.jpg",
      age: 45,
      gender: "Male",
      email: "michael.chen@hospital.com",
      status: "Absent",
    },
    {
      id: 10,
      doctorName: "Dr. Omar El-Hareery",
      doctorImage: "/avatars/doctor1.jpg",
      age: 40,
      gender: "Male",
      email: "omar.elhareery@hospital.com",
      status: "Available",
    },
    {
      id: 11,
      doctorName: "Dr. Sarah Johnson",
      doctorImage: "/avatars/doctor2.jpg",
      age: 35,
      gender: "Female",
      email: "sarah.johnson@hospital.com",
      status: "Available",
    },
    {
      id: 12,
      doctorName: "Dr. Michael Chen",
      doctorImage: "/avatars/doctor3.jpg",
      age: 45,
      gender: "Male",
      email: "michael.chen@hospital.com",
      status: "Absent",
    },
  ],
};
