export const mockEntries = [
  {
    id: "#DH001",
    date: "2024/01/31 15:00",
    treatment: "Tooth Filling",
    diagnosis: "Cavity",
    affectedTooth: "Lateral Incisor",
    medications: "Aspirin",
  },
  {
    id: "#DH002",
    date: "2024/02/15 14:30",
    treatment: "Root Canal",
    diagnosis: "Severe Decay",
    affectedTooth: "Molar",
    medications: "Antibiotics",
  },
  {
    id: "#DH003",
    date: "2024/02/28 09:00",
    treatment: "Cleaning",
    diagnosis: "Regular Checkup",
    affectedTooth: "All",
    medications: "None",
  },
  {
    id: "#DH001",
    date: "2024/01/31 15:00",
    treatment: "Tooth Filling",
    diagnosis: "Cavity",
    affectedTooth: "Lateral Incisor",
    medications: "Aspirin",
  },
  {
    id: "#DH002",
    date: "2024/02/15 14:30",
    treatment: "Root Canal",
    diagnosis: "Severe Decay",
    affectedTooth: "Molar",
    medications: "Antibiotics",
  },
  {
    id: "#DH003",
    date: "2024/02/28 09:00",
    treatment: "Cleaning",
    diagnosis: "Regular Checkup",
    affectedTooth: "All",
    medications: "None",
  },
  {
    id: "#DH001",
    date: "2024/01/31 15:00",
    treatment: "Tooth Filling",
    diagnosis: "Cavity",
    affectedTooth: "Lateral Incisor",
    medications: "Aspirin",
  },
  {
    id: "#DH002",
    date: "2024/02/15 14:30",
    treatment: "Root Canal",
    diagnosis: "Severe Decay",
    affectedTooth: "Molar",
    medications: "Antibiotics",
  },
  {
    id: "#DH003",
    date: "2024/02/28 09:00",
    treatment: "Cleaning",
    diagnosis: "Regular Checkup",
    affectedTooth: "All",
    medications: "None",
  },
  {
    id: "#DH001",
    date: "2024/01/31 15:00",
    treatment: "Tooth Filling",
    diagnosis: "Cavity",
    affectedTooth: "Lateral Incisor",
    medications: "Aspirin",
  },
  {
    id: "#DH002",
    date: "2024/02/15 14:30",
    treatment: "Root Canal",
    diagnosis: "Severe Decay",
    affectedTooth: "Molar",
    medications: "Antibiotics",
  },
  {
    id: "#DH003",
    date: "2024/02/28 09:00",
    treatment: "Cleaning",
    diagnosis: "Regular Checkup",
    affectedTooth: "All",
    medications: "None",
  },
];
