export const revenueData = [
  { doctor: "Dr. John Doe", value: 15.87 },
  { doctor: "Dr. Jane Smith", value: 8.28 },
  { doctor: "Dr. Emily Johnson", value: 13.02 },
  { doctor: "Dr. Michael Williams", value: 12.38 },
  { doctor: "Dr. Sarah Brown", value: 25.87 },
  { doctor: "Dr. David Wilson", value: 2.86 },
  { doctor: "Dr. Jessica Martinez", value: 9.21 },
  { doctor: "Dr. Christopher Lee", value: 9.84 },
];

export const mockBarData = [
  {
    operation: "Cleaning",
    "Plaque Removal": 137,
    "Tooth Whitening": 96,
    "Fluoride Treatment": 72,
    "X-Rays": 140,
    "Composite Fillings": 0,
    "Amalgam Fillings": 0,
    "Gold Fillings": 0,
    "Ceramic Fillings": 0,
    Braces: 0,
    Invisalign: 0,
    Retainers: 0,
    "Space Maintainers": 0,
    "Gum Surgery": 0,
    "Jaw Surgery": 0,
    "Implant Surgery": 0,
    "Bone Grafting": 0,
    "Simple Extraction": 0,
    "Surgical Extraction": 0,
    "Wisdom Tooth Removal": 0,
    "Root Canal Treatment": 0,
    Dentures: 0,
    "Dental Crowns": 0,
    "Dental Bridges": 0,
  },
  {
    operation: "Fillings",
    "Composite Fillings": 55,
    "Amalgam Fillings": 28,
    "Gold Fillings": 58,
    "Ceramic Fillings": 29,
    "Plaque Removal": 0,
    "Tooth Whitening": 0,
    "Fluoride Treatment": 0,
    "X-Rays": 0,
    Braces: 0,
    Invisalign: 0,
    Retainers: 0,
    "Space Maintainers": 0,
    "Gum Surgery": 0,
    "Jaw Surgery": 0,
    "Implant Surgery": 0,
    "Bone Grafting": 0,
    "Simple Extraction": 0,
    "Surgical Extraction": 0,
    "Wisdom Tooth Removal": 0,
    "Root Canal Treatment": 0,
    Dentures: 0,
    "Dental Crowns": 0,
    "Dental Bridges": 0,
  },
  {
    operation: "Orthodontics",
    Braces: 133,
    Invisalign: 52,
    Retainers: 43,
    "Space Maintainers": 83,
    "Plaque Removal": 0,
    "Tooth Whitening": 0,
    "Fluoride Treatment": 0,
    "X-Rays": 0,
    "Composite Fillings": 0,
    "Amalgam Fillings": 0,
    "Gold Fillings": 0,
    "Ceramic Fillings": 0,
    "Gum Surgery": 0,
    "Jaw Surgery": 0,
    "Implant Surgery": 0,
    "Bone Grafting": 0,
    "Simple Extraction": 0,
    "Surgical Extraction": 0,
    "Wisdom Tooth Removal": 0,
    "Root Canal Treatment": 0,
    Dentures: 0,
    "Dental Crowns": 0,
    "Dental Bridges": 0,
  },
  {
    operation: "Surgery",
    "Gum Surgery": 81,
    "Jaw Surgery": 80,
    "Implant Surgery": 112,
    "Bone Grafting": 35,
    "Plaque Removal": 0,
    "Tooth Whitening": 0,
    "Fluoride Treatment": 0,
    "X-Rays": 0,
    "Composite Fillings": 0,
    "Amalgam Fillings": 0,
    "Gold Fillings": 0,
    "Ceramic Fillings": 0,
    Braces: 0,
    Invisalign: 0,
    Retainers: 0,
    "Space Maintainers": 0,
    "Simple Extraction": 0,
    "Surgical Extraction": 0,
    "Wisdom Tooth Removal": 0,
    "Root Canal Treatment": 0,
    Dentures: 0,
    "Dental Crowns": 0,
    "Dental Bridges": 0,
  },
  {
    operation: "Extractions",
    "Simple Extraction": 109,
    "Surgical Extraction": 23,
    "Wisdom Tooth Removal": 34,
    "Root Canal Treatment": 152,
    "Plaque Removal": 0,
    "Tooth Whitening": 0,
    "Fluoride Treatment": 0,
    "X-Rays": 0,
    "Composite Fillings": 0,
    "Amalgam Fillings": 0,
    "Gold Fillings": 0,
    "Ceramic Fillings": 0,
    Braces: 0,
    Invisalign: 0,
    Retainers: 0,
    "Space Maintainers": 0,
    "Gum Surgery": 0,
    "Jaw Surgery": 0,
    "Implant Surgery": 0,
    "Bone Grafting": 0,
    Dentures: 0,
    "Dental Crowns": 0,
    "Dental Bridges": 0,
  },
  {
    operation: "Other",
    Dentures: 66,
    "Dental Crowns": 89,
    "Dental Bridges": 54,
    "Plaque Removal": 0,
    "Tooth Whitening": 0,
    "Fluoride Treatment": 0,
    "X-Rays": 0,
    "Composite Fillings": 0,
    "Amalgam Fillings": 0,
    "Gold Fillings": 0,
    "Ceramic Fillings": 0,
    Braces: 0,
    Invisalign: 0,
    Retainers: 0,
    "Space Maintainers": 0,
    "Gum Surgery": 0,
    "Jaw Surgery": 0,
    "Implant Surgery": 0,
    "Bone Grafting": 0,
    "Simple Extraction": 0,
    "Surgical Extraction": 0,
    "Wisdom Tooth Removal": 0,
    "Root Canal Treatment": 0,
  },
];
